/opt/conda/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:658: Checkpoint directory /workspace/auto-avsr/exp/oulu_front exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/opt/conda/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

  | Name  | Type | Params | Mode
---------------------------------------
0 | model | E2E  | 238 M  | train
---------------------------------------
238 M     Trainable params
0         Non-trainable params
238 M     Total params
955.192   Total estimated model params size (MB)
561       Modules in train mode
0         Modules in eval mode
Sanity Checking DataLoader 0:   0%|                                                                                                                                                           | 0/2 [00:00<?, ?it/s]WER computation error at step 0: selected index k out of range
WER computation error at step 0: selected index k out of range
WER computation error at step 0: selected index k out of range
WER computation error at step 0: selected index k out of range
WER computation - Step 0: 1.0000 (samples: 0/4)
Epoch 0:   0%|                                                                                                                                                                               | 0/59 [00:00<?, ?it/s]WER computation error at step 0: selected index k out of range
WER computation error at step 0: selected index k out of range
WER computation error at step 0: selected index k out of range
WER computation error at step 0: selected index k out of range
WER computation - Step 0: 1.0000 (samples: 0/4)
Epoch 50:  85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 50/59 [07:35<01:22,  0.11it/s, v_num=q74z]WER computation error at step 3000: selected index k out of range
WER computation error at step 3000: selected index k out of range                                                                                                                                                   
/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:434: It is recommended to use `self.log('loss', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
WER computation error at step 3000: selected index k out of range
WER computation error at step 3000: selected index k out of range
WER computation - Step 3000: 1.0000 (samples: 0/4)
Epoch 115: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 59/59 [08:49<00:00,  0.11it/s, v_num=q74z]
                                                                                                                                                                                                                    
Traceback (most recent call last):
  File "/workspace/auto-avsr/train.py", line 212, in <module>
    cli_main()
  File "/workspace/auto-avsr/train.py", line 207, in cli_main
    trainer.fit(model=modelmodule, datamodule=datamodule, ckpt_path=args.ckpt_path)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1012, in _run
    results = self._run_stage()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1056, in _run_stage
    self.fit_loop.run()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 216, in run
    self.advance()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 455, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 153, in run
    self.on_advance_end(data_fetcher)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 394, in on_advance_end
    self.val_loop.run()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 120, in run
    self.setup_data()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 176, in setup_data
    dataloaders = _request_dataloader(source)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 326, in _request_dataloader
    return data_source.dataloader()
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 293, in dataloader
    return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 198, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/workspace/auto-avsr/datamodule/data_module.py", line 151, in val_dataloader
    dataset = AVDataset(
  File "/workspace/auto-avsr/datamodule/av_dataset.py", line 47, in __init__
    self.list = self.load_list(label_path)
  File "/workspace/auto-avsr/datamodule/av_dataset.py", line 55, in load_list
    for path_count_label in open(label_path).read().splitlines():
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/auto-avsr/oulu/labels/val.csv'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/auto-avsr/train.py", line 212, in <module>
[rank0]:     cli_main()
[rank0]:   File "/workspace/auto-avsr/train.py", line 207, in cli_main
[rank0]:     trainer.fit(model=modelmodule, datamodule=datamodule, ckpt_path=args.ckpt_path)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 599, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1012, in _run
[rank0]:     results = self._run_stage()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1056, in _run_stage
[rank0]:     self.fit_loop.run()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 216, in run
[rank0]:     self.advance()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 455, in advance
[rank0]:     self.epoch_loop.run(self._data_fetcher)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 153, in run
[rank0]:     self.on_advance_end(data_fetcher)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 394, in on_advance_end
[rank0]:     self.val_loop.run()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 179, in _decorator
[rank0]:     return loop_run(self, *args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 120, in run
[rank0]:     self.setup_data()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 176, in setup_data
[rank0]:     dataloaders = _request_dataloader(source)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 326, in _request_dataloader
[rank0]:     return data_source.dataloader()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 293, in dataloader
[rank0]:     return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 198, in _call_lightning_datamodule_hook
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/workspace/auto-avsr/datamodule/data_module.py", line 151, in val_dataloader
[rank0]:     dataset = AVDataset(
[rank0]:   File "/workspace/auto-avsr/datamodule/av_dataset.py", line 47, in __init__
[rank0]:     self.list = self.load_list(label_path)
[rank0]:   File "/workspace/auto-avsr/datamodule/av_dataset.py", line 55, in load_list
[rank0]:     for path_count_label in open(label_path).read().splitlines():
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: '/workspace/auto-avsr/oulu/labels/val.csv'
